# Generated by Django 2.0.4 on 2018-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=30)),
                ('InterestedCourse', models.CharField(max_length=30)),
            ],
        ),
    ]
